apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-resources1
  labels:
    app: nginx-resources1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-resources1
  template:
    metadata:
      labels:
        app: nginx-resources1
    spec:
      containers:
      - name: nginx-resources1
        image: nginx
        ports:
        - name: http
          protocol: TCP
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 20
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"