version: '3.7'

services:
  ubuntu:
    build:
      context: ./
      dockerfile: ./dockerfile
    networks:
      - network-backend

  nginx:
    image: nginx
    ports:
      - "3333:80"
    networks:
      - network-backend

networks:
  network-backend: